# Generated by Django 4.0.4 on 2022-04-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('gpa', models.FloatField(max_length=5)),
                ('level', models.CharField(choices=[('lvl 1', 'level one'), ('lvl 2', 'level two'), ('lvl 3', 'level three'), ('lvl 4', 'level four')], max_length=64)),
                ('hour', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
