# Generated by Django 4.0.4 on 2022-04-24 05:17

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_studentuser_managers_studentuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='img',
            field=models.ImageField(default='', upload_to=userapp.models.uploat_to, verbose_name='image'),
        ),
    ]
